### ISSUE TITLE
Extending to also support OpenAI?

### ISSUE THREAD

**Issue by NicolaiSchmid** [r2d4/parserllm#5]
You currently use the transformers library to access the models. 
But except for falcon, most models of HF lack either a commercial licence or in performance.

Would you be open to also support calling into the OpenAI library (Azure & non-Azure) and utilizing the [logit_bias](https://platform.openai.com/docs/api-reference/chat/create#chat/create-logit_bias) attribute of the OpenAI API.

It's a feature that I need in my current workflow

**Comment by r2d4** [comment]
Happy to support the OpenAI models. The one problem is that the ChatGPT tokenizer vocabulary isn't public, so we don't know the full vocabulary. That's necessary because ReLLM/ParserLLM needs to filter from the full set of tokens. I'm not exactly sure what the answer here is yet, but open to suggestions.

**Comment by NicolaiSchmid** [comment]
It's not? 
https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken
https://github.com/openai/tiktoken/blob/5d970c1100d3210b42497203d6b5c1e30cfda6cb/tiktoken_ext/openai_public.py#L63
